### ISSUE TITLE
HTML display for first testimonia test records

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#1]
@davidamichelson, @wsalesky I have uploaded the first draft data of the "testimonia" (these are the records that will be similar to a Text Corpus module). 

Here is their location in the repo: https://github.com/srophe/caesarea-data/tree/master/data/testimonia/tei

We are ready to start working on the display for this data! Please go ahead and throw these up either on the dev server or a local install of the app, and we'll see what they look like and what edits we might need at that time.

Thanks much! Let me know if I need to clarify or expand on any of the above.

**Comment by wsalesky** [comment]
Local install, no modifications: 

<img width="1426" alt="Screen Shot 2020-02-27 at 10 18 02 PM" src="https://user-images.githubusercontent.com/1168206/75507476-2ac62900-59af-11ea-90cb-33ce24bee355.png">

**Comment by wsalesky** [comment]
@wlpotter I will install it on dev tomorrow so you can take a look.

**Comment by wsalesky** [comment]
Here is it is on the dev server: 
Main page: http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/index.html
Browse: http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/browse.html 
Record: http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/testimonia/50

You can start posting issues.

**Comment by wlpotter** [comment]
The display issues have begun to be posted in the app repository: https://github.com/srophe/caesarea/issues

I have made a few edits to the underlying data format based upon the issues posted on the app repo. Here are those edits: https://github.com/srophe/caesarea-data/commit/b4f12b7fe035b0925eda2000fc65307b404172de

**Comment by davidamichelson** [comment]
Just reopening this issue with a request for Winona to load the new version of the data in please (at your convenience and not when you are on vacation :)

**Comment by wsalesky** [comment]
@wlpotter @davidamichelson I added the new version of the data and added webhooks. Let me know if you run into any problems with the webhooks. They are pulling from master at the moment, since we only have the one branch and the one server.
