### ISSUE TITLE
Add function in post-processing will convert " | " to a tei:lb

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#100]
Note that we are currently using the pipe character, "|", to signify line breaks in testimonia sources. We should decide how in the TEI we want to encode this and figure out a way to make this change (potentially a clever regex could handle it)

**Comment by wlpotter** [comment]
56 instances of "|" in our data; what do we want to replace with? `<lb/>` seems a natural choice?

This should be an easy find-and-replace. Do we need an app issue for display?

**Comment by davidamichelson** [comment]
Discuss with Joe future encoding and also how to display the linebreak if at all.

**Comment by wlpotter** [comment]
No whitespace on either side; make an issue for rendering as the start of a new line

**Comment by wlpotter** [comment]
App issue created: https://github.com/srophe/caesarea/issues/291

**Comment by wlpotter** [comment]
Note: I have moved the documentation update to a separate issue (#114) since there are several other needed revisions to that section of the documentation

**Comment by wlpotter** [comment]
Note; we'll add this functionality to the post-processor to convert to a tei:lb

**Comment by wlpotter** [comment]
Fixed this in the post-processing script so that " | " is treated as a `<lb/>` element
