### ISSUE TITLE
Add <placeName> tags to mentions of Caeasarea in Edition and Translation sections of the following testimonia.

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#106]
Not sure how widespread this is, but I noticed a few of the newest batch (e.g. 320) that lack placeName tags even though they are marked 'direct reference' and do mention Caesarea by name.

Should be able to search for records with `/TEI/teiHeader/profileDesc/textClass/catRef[@target="#direct"]` **and**  `/TEI/text/body/ab[@type="edition"][not(placeName)]`

**Comment by wlpotter** [comment]
Once these have been changed we will need to regenerate the abstracts by script

**Comment by wlpotter** [comment]
Create a list of which records don't have tagged place names and are marked as "#direct".

**Comment by davidamichelson** [comment]
Discuss with Joe who should do the tagging.

**Comment by davidamichelson** [comment]
Joe, could you please go through the following 13 records and mark the mention of Caesarea in both the edition and the translation? We will discuss the best way to go about this in our meeting.

https://caesarea-maritima.org/testimonia/153
https://caesarea-maritima.org/testimonia/220
https://caesarea-maritima.org/testimonia/222
https://caesarea-maritima.org/testimonia/230
https://caesarea-maritima.org/testimonia/260
https://caesarea-maritima.org/testimonia/272
https://caesarea-maritima.org/testimonia/288
https://caesarea-maritima.org/testimonia/304
https://caesarea-maritima.org/testimonia/307
https://caesarea-maritima.org/testimonia/309
https://caesarea-maritima.org/testimonia/320
https://caesarea-maritima.org/testimonia/322
https://caesarea-maritima.org/testimonia/338

**Comment by josephrife** [comment]
Thanks Dave but dont understand -- I cant do this until our meeting, right? Joe


-----------------------------------------------------------------
Joseph L. Rife
Associate Professor
Department of Classical and Mediterranean Studies
Affiliated Faculty in Anthropology and Religion
Director, The American Excavations at Kenchreai (Greece)
Co-Director, The Caesarea City and Port Exploration Project (Israel)


________________________________

**Comment by wlpotter** [comment]
Send list to Joe

**Comment by josephrife** [comment]
HI Will -- these are basically done, but note that in some cases there is no mention of Caesarea explicitly in the passage, it is just there implicitly. hope that makes sense! Joe


-----------------------------------------------------------------
Joseph L. Rife
Associate Professor
Department of Classical and Mediterranean Studies
Affiliated Faculty in Anthropology and Religion
Director, The American Excavations at Kenchreai (Greece)
Co-Director, The Caesarea City and Port Exploration Project (Israel)


________________________________

**Comment by wlpotter** [comment]
Okay, great! Makes sense!
