### ISSUE TITLE
Missing space before placeName elements in testimonia

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea-data#118]
See missing space in record: https://caesarea-maritima.org/testimonia/341

```the fortress ofCaesarea.```

![Screen Shot 2022-05-05 at 10 03 34 AM](https://user-images.githubusercontent.com/3083773/166953545-a8975128-7959-4dab-9113-764fddfe549f.png)

**Comment by wlpotter** [comment]
I got 260 hits on the regex `\S<placeName>`, so will need a batch change. Careful of a few that have an &mdash; before.

Also look into the post-processor to figure out where the space was lost.

**Comment by wlpotter** [comment]
Data is fixed; I'm leaving this open to check on whether the issue came from the post-processor or not.

**Comment by wlpotter** [comment]
@davidamichelson After looking back at the files both before and after post-processing, it looks like the issue happened during data entry. The versions I got from Joe also had these whitespace issues, so I think the script is off the hook
