### ISSUE TITLE
Please change theset 5 records to series: Encoding volume and part numbers for Aufstieg und Niedergang der römischen Welt publications

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#12]
These are the relevant index links:

http://www.bu.edu/ict/anrw/pub/II/8/index.html

www.bu.edu/ict/anrw/pub/II/18/index.html#a184

We need to decide how we will encode the various volume and part numbers. Each volume is named, e.g. II.8 is "POLITISCHE GESCHICHTE
(PROVINZEN UND RANDVÖLKER: SYRIEN, PALÄSTINA, ARABIEN)".

Perhaps: Record the named volume title as the Book Title; the volume number (e.g. II.8 or II.18.4) as the Volume Number; and the overarching title in the extra field (we have precedence for this with, for example, the _Joint Expedition to Caesarea Maritima_ publications).

**Comment by davidamichelson** [comment]
@wlpotter Let's review this.

**Comment by wlpotter** [comment]
@davidamichelson I have added the three book sections (and associated monographs).

See the Zotero records here:

https://www.zotero.org/groups/2320447/items/5FT3BNM8
https://www.zotero.org/groups/2320447/items/MFYYI9CW
https://www.zotero.org/groups/2320447/items/N6IV3EA4
https://www.zotero.org/groups/2320447/items/P2L8RUNK
https://www.zotero.org/groups/2320447/items/GLJPRQZA

You can close this issue if they look right.

**Comment by wlpotter** [comment]
move multivolumeTitle to Series field. 

volume number move to Series number

**Comment by wlpotter** [comment]
These have been updated.

**Comment by wlpotter** [comment]
We moved these back to use the `multivolumeTitle` key in the extra field, and the volume number. Cf. https://github.com/srophe/caesarea/issues/210
