### ISSUE TITLE
Test to see if adding a TEI:title element in the TEI:desc type="context" results in italics in HTML

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea-data#120]
Will, could you please see if adding a TEI:title element in the TEI:desc type="context" results in italics in HTML? For example, in https://caesarea-maritima.org/testimonia/234 the string "Secrets for Those Faithful to the Cross (Secreta fidelium Crucis)" should be wrapped in TEI:title and hopefully will display as italics.

If this works then we will want to train Joe on how to add this to old and new records.

**Comment by wlpotter** [comment]
@davidamichelson it looks like, currently, the app does not display `//desc/title` in italics. (I've updated https://caesarea-maritima.org/testimonia/234.tei by tagging the string with a tei:title element, and the data on the server _was_ updated by webhooks). Should we make an app issue for the display?

**Comment by wlpotter** [comment]
@davidamichelson app issue opened (https://github.com/srophe/caesarea/issues/342). We need to let the editors know that this is an option and train them on using the 'wrap in tags' hotkey in oXygen.

This may also involve going back through to update existing context data. In either case, I'm leaving this open to discuss.

**Comment by wlpotter** [comment]
Fixed with srophe/caesarea#342
