### ISSUE TITLE
Add Arabic Records

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea-data#121]

**Comment by wlpotter** [comment]
Draft records are in box; need to post-process and upload to GitHub

**Comment by wlpotter** [comment]
@davidamichelson question on this. How do we want to handle respStmts for Taryn?

We have these options currently:

1. a resp for creating/adding the electronic text
2. a resp for adding metadata such as URNs, Zotero bibls, dates, etc.
3. a resp for the TEI encoding

Would Taryn be credited with the first one?

**Comment by wlpotter** [comment]
Okay, I will add her as the person responsible for creating/adding the text (no. 1). Since it looks from Zotero like you added the bibls there, I'll keep you as nos. 2 and 3. Taryn will be listed as one of the entry creators for these records, which I assume is what we want?

**Comment by wlpotter** [comment]
Closing this as they are up; feel free to open other issues (or send notes via email) for changes to the Arabic records.
