### ISSUE TITLE
whitespace around placeName

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#128]
[This issue](https://github.com/srophe/caesarea/issues/323) is actually a data issue.

This will need a find-and-replace; or I'll need to dive back in to troubleshooting whitespace in basex

**Comment by davidamichelson** [comment]
@wsalesky Can you help us understand if we need to change the data or change the serialization into HTML?

Here is the code:
![Screen Shot 2022-09-23 at 3 20 38 PM](https://user-images.githubusercontent.com/3083773/192050798-87623de1-9c63-4ff4-a8fd-19fde744e5ee.png)


And here is the problem, it looks like the new line breaks before and after the TEI:quote elements are becoming spaces that we do note want:
![Screen Shot 2022-09-23 at 3 20 56 PM](https://user-images.githubusercontent.com/3083773/192050821-73dc9787-7db1-4c26-bea2-de7a5f7a1e83.png)


Thanks

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter which record is this? (Link to github is fine)

**Comment by wlpotter** [comment]
It's this record: https://github.com/srophe/caesarea-data/blob/master/data/testimonia/tei/214.xml

And [these lines](https://github.com/srophe/caesarea-data/blob/master/data/testimonia/tei/214.xml#L271-L275) in particular.

Though I think this issue affects most, if not all, records

**Comment by wlpotter** [comment]
This is either an issue with BaseX's indentation setting (i.e., it's trying to 'pretty print' the output and introducing meaningful whitespace). Two options:

1. Change BaseX output settings to stop adding whitespace in this way
2. If that doesn't work, we can do a find and replace to remove this whitespace.

**Comment by wlpotter** [comment]
Note to self (and thanks @wsalesky for the suggestion) setting BaseX's options to _not_ indent the xml output

- `set serializer indent=no` (this is for the general output of the query)
- `set exporter indent=no` (this is for the output when running update queries that are written to disk)
