### ISSUE TITLE
Update to TEI langUsage

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea-data#132]
Please update template to allow two drop down boxes for langUsage/language on form and in the template.

- Original Language
- Language represented in this edition

Please use the "ana" attribute and point to a taxonomy.

**Comment by wlpotter** [comment]
Here's what this will look like:

In the `//profileDesc/langUsage` we'd have:
```
<langUsage>
  <language ana="#caesarea-original-language" ident="grc">Ancient Greek</language>
  <language ana="#caesarea-represented-language" ident="syr">Syriac</language>
</langUsage>
```

These would point to a `//classDecl/taxonomy[@xml:id="CM-Language-Usage"]`:

```
<taxonomy xml:id="CM-Language-Usage">
  <desc>The <title>Caesarea-Maritima.org Language Usage</title> taxonomy describes how language codes applied to individual testimonia records should be interpreted. These are used in the <att>ana</att> attributes in the elements found in the <gi>langUsage</gi>.</desc>
<category xml:id="caesarea-original-language">
  <catDesc>The original language of a testimonia's composition, which may differ from the linguistic expression recorded in the testimonia record. For example, Severus of Antioch's Letters were originally composed in Greek but survive only in an ancient Syriac translation. This category would record the original language, i.e. Greek.</catDesc>
</category>
<category xml:id="caesarea-represented-language">
  <catDesc>The linguistic expression recorded in this particular testimonia record, even if that expression differs from the original language of composition. For example, Severus of Antioch's Letters were originally composed in Greek but survive only in an ancient Syriac translation. This category would record the extant expression, i.e. Syriac.</catDesc>
</category>
```

@davidamichelson here's a first stab at an implementation for this. Feel free to edit this comment or add a revised version below.

Note to self on what would need to be changed:

- [ ] add the additional taxonomy to all current data
- [ ] add the `@ana` attributes, and corresponding values, for the original language to current data (use the `//langUsage/language` that is already there for the original language)
- [ ] add an additional language under `//langUsage` for the represented language. This should, by default in current data, be the same language code.
- [ ] add the additional taxonomy to the data template
- [ ] add the `@ana` attributes, and an additional `language` element to the data template
- [ ] let Joe know of this change in case he wants to update any of the current data, or the ones he's working on
- [ ] add CSS rules to the form to show and distinguish these two language selections (note: the represented language should be left blank unless it's different)
- [ ] add to the post-processor so it handles copying the original when the represented language is left blank
- [ ] will this need an app issue to change how browse works or how display of the language(s) works?

**Comment by wlpotter** [comment]
This is approved to implement. Using "language-of-testimonia" and "language-of-original". Need to revise the example above (and review the catDesc text nodes).

**Comment by wlpotter** [comment]
One question to answer here is how to handle records where they are the same. I don't like the idea of leaving off the 'original' language and assuming it's the same if it doesn't exist. (Maybe we can leave it blank in the data input, but have the script copy the values over).

On the frontend, though, we might want to hide it unless they are different? It might be confusing to read

```
Language of Testimonia: Greek
  Language of Original: Greek
```

**Comment by wlpotter** [comment]
FYI @davidamichelson I've only implemented this so far in record 405. It'll have to wait until after the conference for me to implement across all records. We'll likely want to do some spreadsheet-based reviews of this kind of data anyway, so we can maybe work on it then.

**Comment by wlpotter** [comment]
The taxonomy language is approved and ready to implement in all records.

**Comment by wlpotter** [comment]
This should be fixed everywhere and ready to go for new data. In new data, if the language of origin is not set by the user, it will be assumed to be the same as the language of testimonia.
