### ISSUE TITLE
Add Genre or Source Type

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea-data#142]
Add this as an additional way to sort the testimonia

**Comment by wlpotter** [comment]
A few notes on this

- we will want a controlled vocabulary for these terms (is there something already created that we could use? Might need to pull from several if there aren't cross-disciplinary agreements between, e.g., classics and late antiquity or Greek and Syriac)
- add as a another taxonomy in the `classDecl`; maybe `@xml:id="CM-Testimonia-Genre"`? Or is that too restrictive? The direct/indirect is currently `//classDecl/taxonomy[@xml:id="CM-Testimonia-Type"]`
    - it could get tricky if we decide to pull this from mulitple sources.
- The declaration will be made in the `//profileDesc/textClass/catRef`, with a `@scheme` attribute pointing to the taxonomy's `@xml:id`
- Add as options in the new data template with a CSS rule enabling a drop-down (or will we allow multiple values? in which case make it checkboxes)

**Comment by wlpotter** [comment]
Same as #156. closing as duplicate
