### ISSUE TITLE
Authors names and titles of works need to match between record header and "About this Text" box to right

### ISSUE THREAD

**Issue by josephrife** [srophe/caesarea-data#148]
There are variations between these in some cases (e.g. 46). In general the personal names/titles in "About this Text" are the correct ones

**Comment by davidamichelson** [comment]
Citations don't match: 751.25-33, 751.25-37

**Comment by davidamichelson** [comment]
@wlpotter will re-run the script and it should fix everything

**Comment by wlpotter** [comment]
This should be fixed. I'll run an update to the abstracts as well, just to be safe
