### ISSUE TITLE
Remove quotations from testimonia edition and translation excerpts

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#15]
We would like to remove the quotation marks from the excerpts on testimonia records.

@wsalesky I believe the quotation marks appear because these excerpts are wrapped in a tei:quote element, is that correct?

If so, I will make this change in the data; otherwise I can open an issue in the app repo for this change.

For reference, see http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/testimonia/44

**Comment by wsalesky** [comment]
Yes, it is because they appear in a tei:quote element.

**Comment by wlpotter** [comment]
Quotes removed; leaving open to get feedback from editors.

Note: will need to change how transform script outputs the excerpts. In particular the source attributes will need to be moved to the tei:ab rather than the removed tei:quote

**Comment by wlpotter** [comment]
Fixed.
