### ISSUE TITLE
Pipe-character--is that what it's called? the tall vertical bar -- as entered on XML data-entry files does not always show up as a hard return in formated text shown on website

### ISSUE THREAD

**Issue by josephrife** [srophe/caesarea-data#150]
Sometimes where I have entered the "pipe" -- i.e. "|" -- it generates a hard return in the file as seen on web, but sometimes it just shows as a pipe on the website. I tried to enter these always as a pipe flanked by one space on each side, i.e. " | " but that might be at the root of the problem? The records where pipes show up on the web-record where they should not are the following, I think I found them all in this list?: 406, 408, 411, 412. On the other hand, some are all good: 63, 408, 407

**Comment by wlpotter** [comment]
Note to self:

- [ ] fix in current data
- [ ] troubleshoot why this isn't working in the post-processor
