### ISSUE TITLE
Bad date formatting in "About This Text" in individual records

### ISSUE THREAD

**Issue by josephrife** [srophe/caesarea-data#153]
There is something wrong with the dates in that content-area in the following records: 43, 46, 48, 220, 329 (there could be more). The website is showing the dates as entered in xml files (e.g. 0419 0420) and not converted into the standard format for viewing (i.e. 419 - 420 CE).

**Comment by wlpotter** [comment]
Note to self:

- [ ] Remove the text nodes of origin dates that weren't processed correctly. Find with `>0.+</origDate>` in `//profileDesc/creation/origDate` and replace with `/>` to leave those elements empty
- [ ] Update the processor so it ignores elements with non-empty text nodes and then re-run that function on current data. This should only update the records that have 
- [ ] Create a separate issue to allow the human readable text node to be edited in the data template. This will allow the editors to either update current date information and also provide alternatives to the "419 - 420 CE" format as needed. The updates to the processor will then ignore these filled-in dates. Might need an option to override but that gets tricky
