### ISSUE TITLE
Fixing attribution of translation vs editing at bottom of each record

### ISSUE THREAD

**Issue by josephrife** [srophe/caesarea-data#154]
Ideally at the end of each record under "How to City this Entry," it should read e.g. "[enter translators/main handlers name, e.g. David Michelson, or Taryn Marashi], “Palladius of Galatia, History for Lausus 64,” in Joseph L. Rife et al., eds., Caesarea Maritima: A Collection of Testimonia, last modified August 9, 2021, https://caesarea-maritima.org/testimonia/329. {e.g.} I suppose this means adding a data-entry box in the XML editing template that just allows us to enter "Translator" and unique name, perhaps from drop-down menu. I believe we talked about this with Dave, right? thx

**Comment by davidamichelson** [comment]
Clean up and update the About this Entry.

**Comment by davidamichelson** [comment]
Changes:

If the XML editor was also the XML translator, they should appear as first author on the citation.

Fix first author.

Also under Authorial and Editorial Responsibility add translator note as resp statement.

Need to update.

Also re-order the listing of Authorial and Editorial Responsibility to start with entry contributors and end with general editor.

Also why are the technical editors listed with the entry: David A. Michelson and William L. Potter, technical editors, “al-Yaʿqūbī, Book of Lands 115-116”

**Comment by wlpotter** [comment]
@davidamichelson I think this one may need a bit more discussion. There are going to be a few changes associated with it, as far as I can tell:

1. Current data needs to be updated semi-manually to ensure that the right individuals are attributed with the right language describing their contributions -- and in the right order.
2. Once we've sorted out the desired order and language, the data template and data entry form should be updated to allow for the kinds of responsibilities we want to capture
3. There may be additional post-processing updates depending on how we handle the data template
4. I think we can handle this all on the data side, but there might also be display updates needed.

To begin, we should sort out at our next meeting the kinds of contributions we want to record, and their order of priority.

**Comment by josephrife** [comment]
A quick response to this from Dave -- I am happy to discuss this. I would however note that I have consistently applied them to the large majority of records; and the language is laid out and explained in the Prolegomena document. all best Joe


-----------------------------------------------------------------
Joseph L. Rife
Associate Professor
Department of Classical and Mediterranean Studies
Affiliated Faculty in Anthropology and Religion
Director, The American Excavations at Kenchreai (Greece)
Co-Director, The Caesarea City and Port Exploration Project (Israel)


________________________________

**Comment by wlpotter** [comment]
Note to self: 

These are the kinds of responsibilities we want to track in the tei:respStmt elements (we'll also want to update the data entry form to allow more of these)

- identified
- translated
- transcribed
- data entered into TEI
- edited

**Comment by davidamichelson** [comment]
add one more: research assistance

**Comment by wlpotter** [comment]
Note to self: include here, or as its own issue, updating the order of `editor[@role="creator"]` so that editors other than Joe are listed first. This should also be reordered in current data

**Comment by davidamichelson** [comment]
We should define these terms in the documentation wiki

**Comment by wlpotter** [comment]
The following will merit an `editor[@role="creator"]`: "identified"; "translated"; "transcribed

**Comment by davidamichelson** [comment]
```@role=creator``` will be given for the following roles:

    identified
    translated
    transcribed
    edited (in rare cases only)

Otherwise, these four 

data entered into TEI
edited
editorial review by
research assistance by

will be noted in respStmt only

**Comment by josephrife** [comment]
Quick question: what does "identified" mean? Does that designate the person who found the passage in said author, i.e. added the testimonium to the running list of total testimonia on Caesarea?

-----------------------------------------------------------------
Joseph L. Rife
Associate Professor
Department of Classical and Mediterranean Studies
Affiliated Faculty in Anthropology and Religion
Director, The American Excavations at Kenchreai (Greece)
Co-Director, The Caesarea City and Port Exploration Project (Israel)


________________________________

**Comment by josephrife** [comment]
I guess I mean: if I have defined the act of "identification" accurately, is that an act that deserves special designation in our system? Not sure I follow.

-----------------------------------------------------------------
Joseph L. Rife
Associate Professor
Department of Classical and Mediterranean Studies
Affiliated Faculty in Anthropology and Religion
Director, The American Excavations at Kenchreai (Greece)
Co-Director, The Caesarea City and Port Exploration Project (Israel)


________________________________

**Comment by josephrife** [comment]
No offense but I dont follow what it means to designate someone for "research assistance" on a given testimonium. vague?

-----------------------------------------------------------------
Joseph L. Rife
Associate Professor
Department of Classical and Mediterranean Studies
Affiliated Faculty in Anthropology and Religion
Director, The American Excavations at Kenchreai (Greece)
Co-Director, The Caesarea City and Port Exploration Project (Israel)


________________________________

**Comment by wlpotter** [comment]
@josephrife hopefully I can clarify a bit:

1. On "identified", you are correct that this will be the person who determined that a particular passage in a pre-modern work was in fact a testimonium for Caesarea, and so added that record to the running list. I would say that this would be worth crediting the person as an entry 'creator'/'contributor', as the entry would not be included in the database without their intellectual contribution of identifying the testimonium. That was my thinking, at least
2. For "research assistance", this is somewhat vague, but it could be useful to have a as a catch-all term for work done on a record, particularly by undergraduate or even graduate RAs, for which we want to credit the person but which does not fall into the other categories. An example might be if someone entered the testimonia information but had a student lookup and add the Pleiades links for the places of composition. There could be any number of small contributions that it would be difficult to make an exhaustive list

**Comment by wlpotter** [comment]
These have been added to the data template, and the post-processing script should handle the new way of giving credit for each of these. I will leave this issue open to review and make sure we are all agreed on the list and the meaning of each one

**Comment by josephrife** [comment]
Thanks Will. It will be important to get Dave's input.

-----------------------------------------------------------------
Joseph L. Rife
Associate Professor
Department of Classical and Mediterranean Studies
Affiliated Faculty in Anthropology and Religion
Director, The American Excavations at Kenchreai (Greece)
Co-Director, The Caesarea City and Port Exploration Project (Israel)


________________________________

**Comment by davidamichelson** [comment]
Thanks @josephrife and @wlpotter I like both of these the "identified by" person deserves credit for identifying the testimonium in the first place (usually this is you Joe) and that person should get credit in the citation. 

"Research assistance by" is more vague I agree, but we do need a way to make sure that undergrad assistants get their name mentioned somewhere for their work. This "research assistance by" credit, however, will not rise to the level of being in the citation of the record. It will just be listed in the section listing who did what. Also this "research assistance by" could always be edited by hand to be more specific if desired.

**Comment by wlpotter** [comment]
Closing this issue since we discussed today and agree on the current list
