### ISSUE TITLE
Fix Arabic text in record al-Yaʿqūbī, Book of Lands 115-116 = testimonium 395

### ISSUE THREAD

**Issue by josephrife** [srophe/caesarea-data#157]
In this record the Arabic text needs two fixes: 1) justify right; 2) it should be in the same point-size as other Arabic texts, e.g. the two by Al-Muqqadasi, numbers 393 and 394 (there the Arabic is larger and probably easier to read)  thx

**Comment by davidamichelson** [comment]
`<ab type="edition" xml:lang="lara" xml:id="quote395-1">`

problem with lang code
