### ISSUE TITLE
Erroneous inclusion of several periods under "Historical era composed" in the box "About This Text" in certain records

### ISSUE THREAD

**Issue by josephrife** [srophe/caesarea-data#159]
The offending records I have found so far are testimonia numbers 1, 43, 44, 220, 413, 414

**Comment by davidamichelson** [comment]
Two issues:
1. Fix the 0007 0024 date @wlpotter 
2. Make issue for Winona to put the different periods on a new line @davidamichelson

**Comment by wlpotter** [comment]
The indentation issue was fixed (https://github.com/srophe/caesarea/issues/374). The date format issue is the same as (and will be solved by) #153
