### ISSUE TITLE
Update editors' preferred names for publication

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#16]
Should be Joseph L. Rife; update in the current data and make sure the script outputs properly

Ask Phil his preference.

**Comment by wlpotter** [comment]
"Joseph L. Rife" updated; reaching out to Phil for his preference.

**Comment by davidamichelson** [comment]
link to #18

**Comment by wlpotter** [comment]
"Phillip I. Lieberman" has been added to editors.xml. Will replace in existing data.
