### ISSUE TITLE
The licence text should update based on entry contributors

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#176]
In #161 we are updating the year listed in the copyright portion of the licence text based on the most recent `//publicationStmt/date` element.

We also, in that same element, have text that reads

>this entry is copyright DATE by the contributors (Joseph L. Rife, et al.) and the Caesarea City and Port Exploration Project.

This is hard-coded in the record. In #175 we are re-ordering the entry contributors so that JLR is not listed first in every case. While we have the script updating the date, should we go ahead and have it update the contributors list to grab the first `editor[@type="creator"]` text node?

**Comment by davidamichelson** [comment]
Yes, please do!

**Comment by wlpotter** [comment]
Use the `//titleStmt/editor[@role="creator"][1]/text()` to supply the contributor name
