### ISSUE TITLE
editor URIs and strings for testimonia and bibl encoders

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#18]
We need to sort out the editor URIs, particularly for the encoders who have created both bibl and testimonia records as their URI token may not match. (e.g. "itsbianca" vs. "bgardner").

Should we base the editors.xml URI token on the Zotero username token? Or do we need to create a lookup somewhere?

This is somewhat related to https://github.com/srophe/caesarea/issues/33

**Comment by davidamichelson** [comment]
@wlpotter Please create an editors.xml file
@davidamichelson will create an issue for how to handle zotero

**Comment by wlpotter** [comment]
editors.xml has been created and updated to include all project members to date. 

@davidamichelson I included Dan since I can't remember if we have (or will) asked for any schema customization for Caesarea?

**Comment by davidamichelson** [comment]
Need to work out:

- [ ] Use in Zotero

- [ ] Include Dan

**Comment by davidamichelson** [comment]
@wlpotter Can we close this issue and create a new one about schema?
