### ISSUE TITLE
interlinking container and nested testimonia

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#19]
How will we link nested testimonia with their container testimonia?

Perhaps use tei:listRelation? Have contained/nested testimonia point to the container record?

**Comment by wlpotter** [comment]
Will need a separate issue in the app for how we will display these links.

**Comment by wlpotter** [comment]
https://github.com/srophe/caesarea/issues/57 for the app changes.
https://github.com/srophe/caesarea-data/issues/20 for the editorial discussion driving these changes.

**Comment by davidamichelson** [comment]
Deprecated
