### ISSUE TITLE
Update data with new module names

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#21]
Once we have finalized the names for the modules, we will need to update the data.

For testimonia records, this will be in the following xpaths:

- `/TEI/teiHeader/fileDesc/titleStmt/title[@level="m"]`; "Caesarea Maritima: Literary and Documentary Testimonia" -> Testimonia module name
- (potentially) `/TEI/teiHeader/fileDesc/publicationStmt/authority` "Ceasarea City and Port Exploration Project" -> Main Site Name

Will update this issue once names have been decided on; will also add information for the bibl module.

**Comment by davidamichelson** [comment]
Need name for bibl module

**Comment by wlpotter** [comment]
FYI here is what I have on names from meeting with the editors on 2020-04-17:

Full site: "Caesarea-Maritima: A Digital Archive"
Testimonia module: "Textual Evidence for Caesarea-Maritima"

**Comment by davidamichelson** [comment]
A Comprehensive Bibliography of Caesarea Maritima

**Comment by wlpotter** [comment]
These names have been updated in the testimonia data. As bibl records are generated from Zotero, we will need to change this on the app.

**Comment by wlpotter** [comment]
In writing the documentation for the testimonia data, I'm realizing that it would sound better to have an article at the beginning of this module:

"The Textual Evidence for Caesarea Maritima". @davidamichelson thoughts?

**Comment by davidamichelson** [comment]
"A Collection of Textual Evidence for Caesarea Maritima"

**Comment by davidamichelson** [comment]
Need to update in the data.
