### ISSUE TITLE
update tei:bibls in testimonia records to include URNs, author, editor, and title info

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#27]
Current bibls:
 (example from [record 70](https://github.com/srophe/caesarea-data/blob/master/data/testimonia/tei/70.xml#L256-L259))

```
<bibl xml:id="bib70-1">
    <ptr target="https://caesarea-maritima.org/bibl/A5CE8VEG"/>
    <citedRange>10.44-10.48</citedRange>
</bibl>
```

New bibl:
```
<bibl xml:id="bib70-1">
    <title level="m" xml:lang="en">New Testament - Acts: Machine Readable Text</title>
    <editor>Brooke Foss Westcott</editor>
    <editor>Fenton John Anthony Hort</editor>
    <ptr target="https://caesarea-maritima.org/bibl/A5CE8VEG"/>
    <idno type="CTS-URN">urn:cts:greekLit:tlg0031.tlg005.perseus-grc2</idno>
    <citedRange unit="cts-passage">10.44-10.48</citedRange>
</bibl>
```

Notes: 
- Including the CTS-URN would facilitate the linked data box (see https://github.com/srophe/caesarea/issues/47. I will post a comment there about how the app can construct the link to the text from the above data.)
   -  the `@unit="cts-passage"` on the tei:citedRange associates that text node with the URN for this purpose.
- We may need to include an `@xml:base` or other attribute on the tei:idno containing the URN to facilitate the construction of the link out to the text (on Perseus, etc.). This is currently in the Zotero record as the "URL" and could be included in the tei:bibl if needed. It is also in the `/TEI/teiHeader/profileDesc/textClass/classCode/idno[@type="URN"]/@xml:base`. So we have options.

@davidamichelson I can get this data from a JSON export of the Zotero library using XQuery and construct the new bibls quite easily. We should discuss:
1. the `@unit` on citedRange
2. how to include the URL base for linking via URN to the text
3. what changes we will need to make to handle electronic/machine-readable texts which do not have URNs (e.g. those from Schaff in the CCEL).

**Comment by wlpotter** [comment]
A few more thoughts on the base URL/API endpoint. 

There are different endpoints based on whether you are at the text-level or the passage-level of a URN citation.

For example, https://scaife.perseus.org/library/urn:cts:greekLit:tlg0317.tlg001.1st1K-grc1/ takes you to what is essentially the Table of Contents for _Acta Joannis_. 

However, https://scaife.perseus.org/reader/urn:cts:greekLit:tlg0317.tlg001.1st1K-grc1:1 takes you to the first chapter. 

Note the difference between /library and /reader (this is similar to the distinct endpoints of the [DTS specifications](https://distributed-text-services.github.io/specifications/#supported-operations)). You cannot use a URN with a passage citation with the /library base and you must specify a passage in order for the /reader base to return anything.

The original Perseus Digital Library works slightly different but maintains a similar distinction:

http://data.perseus.org/citations/urn:cts:latinLit:phi0448.phi001.perseus-lat1:1.6.2 takes you to the passage 1.6.2 

but http://data.perseus.org/texts/urn:cts:latinLit:phi0448.phi001.perseus-lat1 resolves to the first book, chapter, section (i.e., 1.1.1). However, although the implementation behaves differently, the older PDL has the same restrictions in that you cannot use a passage citation with a /texts URL and you must specif a passage citation with a /citations URL.

The relevance of all this is that in the Zotero records "URL" field we have record the text-level link (e.g. /reader or /texts) but in the `/TEI/teiHeader/profileDesc/textClass/classCode/idno[@type="URN"]/@xml:base` we have recorded the citation-level link (e.g. /reader or /citations). The question is, then, what functionality do we want from the URN? Or do we want both to point to the text-level and to the passage-level? This will change both how we implement the data in the tei:bibls but also how we construct the queries in the linked data box.

**Comment by davidamichelson** [comment]
This will wait until we know more.

**Comment by davidamichelson** [comment]
We will put an IDNO in each AB which has the xmlbase and CTS URN for the passage, even if the CTS URN is not resolvable.

Then when the URN can be resolved, the AB block will conclude with a link to the passage in context at the source.

**Comment by davidamichelson** [comment]
Bibl element (footnote) will not contain the URN. But will have link to URL for source as a whole when possible.

**Comment by davidamichelson** [comment]
About This Text infobox will not have CTS link.

Linked Data box will organize information about URN by related project.

**Comment by wlpotter** [comment]
Data has been updated with an idno element as last child of the `tei:ab[@type="edition|translation"]`. 

There may be a few issues where the data did not transfer properly into the idno element or the xml:base attribute. I will generate a list of these links so that we can see which need to be manually updated and which need a URN to be minted. I will make a separate issue for that process.

**Comment by davidamichelson** [comment]
This can be closed. Noting that it lead to these issues #36 and https://github.com/srophe/caesarea/issues/72
