### ISSUE TITLE
add xml:lang to //profileDesc/creation/title

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#29]
I think we should add an `@xml:lang="en"` to the title in the tei:profileDesc. We are using the standardized English title for the text node of this element and typing the title as `@type="uniform"`, so we should indicate in what language this title appears as the uniform/standardized title.

**Comment by davidamichelson** [comment]
Yes, please do.

**Comment by wlpotter** [comment]
note to self: will need to change in current data's abstract as well. New records will have their abstract generated from the corrected profileDesc, so this will not be an issue at that point.
