### ISSUE TITLE
remove nested tei:date from tei:origDate in profileDesc

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#30]
We have a tei:date nested within the tei:origDate in the profileDesc. for example:

```
<origDate period="#nabateanKingdom #earlyRoman" notBefore="0093" notAfter="0094">
    <date>93 - 94 CE</date>
</origDate>
```

I'm not sure why we decided to have both. Maybe we thought that origDate could not contain character data? But it can, so it seems redundant to have both. Could we change to:

```
<origDate period="#nabateanKingdom #earlyRoman" notBefore="0093" notAfter="0094">93 - 94 CE</origDate>
```

to simplify things?

**Comment by davidamichelson** [comment]
@wsalesky Will this change break anything? We would like the Srophé app to treat TEI:origDate and TEI:date the same.

**Comment by davidamichelson** [comment]
if @wsalesky has no objections then go ahead please

**Comment by davidamichelson** [comment]
@wlpotter Please make the change in the data and if it breaks the display file a bug

**Comment by wlpotter** [comment]
Note to self: this will need to be changed in the abstracts as well for current data. New data's abstracts will be generated from the updated profileDesc/creation, so this will not be an issue.

**Comment by wlpotter** [comment]
Data has been updated. Leaving open to test if this change breaks the display.

**Comment by wsalesky** [comment]
@wlpotter I uploaded the data locally, does not seem to have caused any issues. I will go ahead and add it to dev.
