### ISSUE TITLE
change type attribute in //profileDesc/textClass/classCode/idno

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#31]
This is the idno which contains the URN of the excerpt from the work which makes up the testimonia record. Currently we are just typing this as type="URN", but in the bibl module we have begun to call these URNs "CTS-URN". I think we should make the same change here.

current:
```
<idno xml:base="http://data.perseus.org/citations/" type="URN">urn:cts:greekLit:tlg0526.tlg001:18.55-18.59</idno>
```

proposed:
```
<idno xml:base="http://data.perseus.org/citations/" type="CTS-URN">urn:cts:greekLit:tlg0526.tlg001:18.55-18.59</idno>
```

**Comment by davidamichelson** [comment]
Please make this change.
