### ISSUE TITLE
Tag everything bibliography in Zotero

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea-data#33]
with either Testimonia-Works-Cited
Comprehensive-Bibliography

**Comment by wlpotter** [comment]
Everything that has been added on or before 2020-06-10 has been tagged either as "#Testimonia-Works-Cited" or "#Comprehensive-Bibliography".

There will likely be sources, particularly when we get to the early modern period, that may need both tags. However, I have not tried to sort those out at this time. In other words, all records currently are tagged as belonging to one or the other module, and if we use a record from the Comprehensive Bibliography in the Testimonia Works Cited, we can add the latter tag at that time.

**Comment by davidamichelson** [comment]
Do we need to mark primary source edition and translation

**Comment by davidamichelson** [comment]
Check for after June 10

**Comment by davidamichelson** [comment]
Let's review and close
