### ISSUE TITLE
Some perseus English texts have Greek letters hidden in them

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea-data#37]
See record 104

Starting from that time also Origen’s commentaries on the divine Scriptures had their beginning, at the instigation οf Αmbrose, who not plied him with innumerable verbal exhortations and encouragements, but also provided him unstintingly what was necessary. For as he dictated there were ready at hand mοre than seven shorthand-writers, who relieved each other at fixed times and as many copyists, as well as girls skilled in penmanship; for all of whom Αmbrose supplied without stint the necessary means. Νay further, he contributed to Origen a vast amount of zeal in the earnest study of the divine oracles, a zeal which more than anything else acted as an incentive to him tο compose his commentarieses. Such was the state of affairs when Pontianus succeeded Urban, who had been bishop of the church of the Romans for eight years, and Ζebennus came after Ρhiletus as [bishop] of the [church] of the Antiochenes. In their day Οrigen journeyed to Greece through Palestine because of an urgent necessity in Church matters, and received the laying-on of hands for the presbyterate at <placeName xml:lang="en">Caesarea</placeName> from the bishops there. The agitation that was set on foot concerning him on this account, and the decisions made by those who presided over the churches on the matters agitated, as well as the other contributions that he made as he was reaching his prime to the study of the divine Word, require a separate composition, and we have given a fairly full account of them in the seeond [book] of the Apology that we have written on his behalf.<note type="corrigenda">Inaccuracies found in the transcription of the electronic text compared to its printed source have been corrected.</note>

**Comment by davidamichelson** [comment]
I guess we need to write as script to check for this.

**Comment by davidamichelson** [comment]
Run a regex in Oxygen search in files for ab=translation range - greek unicode

**Comment by wlpotter** [comment]
(This page has some generally useful info for Unicode and regex https://regular-expressions.mobi/unicode.html)

**Comment by wlpotter** [comment]
Here is the RegEx to run: `\p{InGreek}`

use find-in-files on this XPath: `/TEI/text/body/ab[@type="translation"]`

I ran this on the 132 records and have returned 76 results. It is likely we could get a list of which characters (probably need a simple XQuery for that), then we could do a find-and-replace if it's a small set of characters. A quick glance through the results makes it seem that it is a small set (mostly omicron, capital eta, etc.)

**Comment by davidamichelson** [comment]
Okay great, that does sound like the right approach (and perhaps they are
all intended to be Roman capital letters?).

Running find and replace in Oxygen may actually be quicker than even
writing the script.

**Comment by davidamichelson** [comment]
Those Greek letters which have the same form as Latin letters are: capital A, B, E, Z, H, I, K, M, N, O, P, T, Y, X.

**Comment by wlpotter** [comment]
Yes, Oxygen find and replace is probably faster. I think it is mainly those capitals plus lower-case omicron

**Comment by wlpotter** [comment]
I believe I fixed this
