### ISSUE TITLE
Fix CTS-URN idnos with empty xml:base attributes

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#39]
The idnos for the following records have empty xml:base attributes due to an error with their citation link in the testimonia data script. This base should be one of the Perseus library links, but it somehow got lost in data transmission. 

These records should be checked by hand, and their xml:base attribute added back, and their `ref/@target` attribute fixed as well.

urn:cts:greekLit:tlg0018.tlg031.opp-grc1:276-327
urn:cts:greekLit:tlg0031.tlg005.perseus-grc2:10.1
urn:cts:greekLit:tlg0031.tlg005.perseus-grc2:10.24
urn:cts:greekLit:tlg0031.tlg005.perseus-grc2:10.34
urn:cts:greekLit:tlg0031.tlg005.perseus-grc2:6.5
urn:cts:greekLit:tlg0031.tlg005.perseus-grc2:9.30
urn:cts:latinLit:phi0978.phi001.perseus-lat1:5.13
urn:cts:latinLit:phi1351.phi004.perseus-lat2:2.82-2.83
urn:cts:latinLit:stoa0023.stoa001.perseus-eng2:14
urn:cts:latinLit:stoa0023.stoa001.perseus-lat2:14.11

These are records:

- [x] 1
- [x] 67
- [x] 68
- [x] 69
- [x] 65
- [x] 66
- [x] 43
- [x] 44
- [x] 50
- [x] 50

**Comment by wlpotter** [comment]
FYI this is related to #36

**Comment by davidamichelson** [comment]
related to https://github.com/srophe/caesarea/issues/149

**Comment by wlpotter** [comment]
Current (based on record 50): 

Xpath: `/TEI/text/body/ab[@type="edition|translation"]/idno|ref`
```
<idno type="CTS-URN" xml:base="">urn:cts:latinLit:stoa0023.stoa001.perseus-lat2:14.11</idno>
        <ref target="urn:cts:latinLit:stoa0023.stoa001.perseus-lat2:14.11"/>
```

New:

```
<idno type="CTS-URN" xml:base="https://scaife.perseus.org/reader/">urn:cts:latinLit:stoa0023.stoa001.perseus-lat2:14.11</idno>
        <ref target="https://scaife-cts.perseus.org/api/cts?request=GetPassage&amp;urn=urn:cts:latinLit:stoa0023.stoa001.perseus-lat2:14.11"/>
```

Notes:

- We will need to double check that these are all coming from the Scaife library. If not, the xml:base values will have to change.

**Comment by wlpotter** [comment]
These should be fixed, but will double check them before closing

**Comment by wlpotter** [comment]
Remaining issues to sort out

- [ ] 1: this record seems to have several display issues. (see #56 ). Missing 'browse this text' link
- [ ] 43: the Scaife link does not resolve. It's an old Perseus library text, so I need to change the xml:base

**Comment by wlpotter** [comment]
For record 1, see this associated app issue https://github.com/srophe/caesarea/issues/222

**Comment by wlpotter** [comment]
Fixed
