### ISSUE TITLE
Consider Adding Dan Schwartz as a Technical Editor for Schema Customization

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea-data#41]

**Comment by davidamichelson** [comment]
Was part of https://github.com/srophe/caesarea-data/issues/18

**Comment by davidamichelson** [comment]
Approved.

**Comment by wlpotter** [comment]
@davidamichelson should this be a batch change in the teiHeader? Do we need a separate app issue for crediting on the index pages, etc.?

**Comment by davidamichelson** [comment]
Yes please do.

**Comment by wlpotter** [comment]
Added to data; made an app issue [here](https://github.com/srophe/caesarea/issues/298) for updating the app's index and about pages.
