### ISSUE TITLE
Comma in place of publication

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea-data#45]
The Herods of Judaea
Jones, A.H.M. The Herods of Judaea. Oxford,: Clarendon Press, 1967. 
URI: https://caesarea-maritima.org/bibl/UP4436J4

**Comment by davidamichelson** [comment]
@wsalesky Could you give @wlpotter and me a refresher please. If we change the Zotero entry is it dynamically pushed to TEI and to the production server?

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter No you will need to use the zotero2bibl update facility, details in a forthcoming email.

**Comment by wlpotter** [comment]
@wsalesky thanks for this. @davidamichelson  I will update the Zotero records and run the zotero2bibl update.

**Comment by wlpotter** [comment]
Data updated; waiting to close until I run zotero2bibl

**Comment by wlpotter** [comment]
Fixed
