### ISSUE TITLE
Tower of Strato is lowercase

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea-data#46]
https://caesarea-maritima.org/testimonia/94

**Comment by wlpotter** [comment]
@davidamichelson It looks like this record has "tower of strato" in lowercase because that is how the [source translation](https://caesarea-maritima.org/bibl/NA979CSQ) rendered it. I can change it, but we should take an editorial note that we have tacitly harmonized capitalization across records.

**Comment by davidamichelson** [comment]
hmm, interesting, okay leave this open.

**Comment by davidamichelson** [comment]
So we will edit this and we will need to create a way to include an annotation that says we have corrected the texts.

**Comment by wlpotter** [comment]
Fix bibl range for English. Currently 2.1, should be 2.10

**Comment by wlpotter** [comment]
Fixed.
