### ISSUE TITLE
Please change: Textual Evidence for Caesarea-Maritima to Caesarea Maritima: A Collection of Testimonia

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea-data#50]
In the data (and I assume also in the XML transform) we have an old title for the project: "Textual Evidence for Caesarea-Maritima" could you please find and replace in data to update to "Caesarea Maritima: A Collection of Testimonia" and also edit the transform please? Thanks!

**Comment by davidamichelson** [comment]
related to https://github.com/srophe/caesarea/issues/142

**Comment by davidamichelson** [comment]
In addition to changing in the TEI, this also appears in the preview boxes on the map, so we need to check that that changed dynamically when the TEI is changed.

**Comment by wlpotter** [comment]
Leaving open to check that map browse preview boxes were changed.

**Comment by davidamichelson** [comment]
It looks like it was not there, maybe I misremembered?

**Comment by wlpotter** [comment]
It was there, but I think this https://github.com/srophe/caesarea/issues/175 caused the title to disappear?

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter I removed it from the preview box. The title was only supposed to be grabbing title[@level = 'a'] but was pulling in all the titles. We can put if back if you want it (with proper spaces).
