### ISSUE TITLE
How do we want to handle related testimonia?

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#54]
For example, https://caesarea-maritima.org/testimonia/94 is in Eusebius' _Ecclesiastical History_ that is quoting Josephus.

We need to figure out how to handle such cases, particularly how to link the two testimonia together.

**Comment by davidamichelson** [comment]
In the text which is quoting, add a TEI:note referring to the original source
In the About this Text add a Cited By and a Cites link between the two (or more) testimonia.
Future: Add a browse by related texts with a network graph.

**Comment by wlpotter** [comment]
@davidamichelson I don't know if we implemented this in data? Do we want to, and if so do we need an app issue?

**Comment by davidamichelson** [comment]
Discuss with Joe, how we want to encode these and where to display this information.

**Comment by davidamichelson** [comment]
Add this in the related categories, also use it for biblical passages about Caesarea that get commentary

**Comment by wlpotter** [comment]
Note that this is being handled in #183. For 1.0 release we will include hyperlinks to related testimonia as part of the general related subjects panel
