### ISSUE TITLE
Run the script on 62 | Itinerarium Antonini Piacentini | 46

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea-data#55]

**Comment by wlpotter** [comment]
It looks like the following are ready to be converted  but haven't been yet:

62 | Itinerarium Antonini Piacentini | 46
147 | Photius | Bibliotheca | 89
148 | Photius | Bibliotheca | 118

The others in the sprreadsheet need further editing or input from the editors.

**Comment by wlpotter** [comment]
I added 147 and 148 to the db. We have some work-level data missing for 62 that I need to find, but then I will create a record for that as well. That should bring us up to date with the csv records that are ready for conversion

**Comment by wlpotter** [comment]
First post-processing output has been tested on this see #85

**Comment by wlpotter** [comment]
Note from JLR on this record:

>I need to redo the record on the Piacenza Pilgrim so please dont upload to master the one from Eliana, the new one will come along with the new batch I will prepared to fork

I will delete this record from draft-data.
