### ISSUE TITLE
Records without full URNs

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#60]
See, e.g., https://caesarea-maritima.org/testimonia/57

Not all records had URNs (because for some we will need to mint new ones based on TLG or another standardized reference system). Currently the transform script inserted just the section-range into the URN field (`/TEI/teiHeader/profileDesc/textClass/classCode/idno`). 

Eventually we will need to mint URNs, but perhaps for first release we want to figure out a different way of handling these?

I would suggest 

1. Delete the incomplete and invalid URNs in sources for which we need to mint a URN. This will leave some records with an empty CTS-URN idno element.
2. (For now), have the app only display a URN in the "about this text" box if there is one available

@davidamichelson thoughts?

**Comment by davidamichelson** [comment]
We don't need to suppress when empty.

**Comment by davidamichelson** [comment]
When done, we will create a new issue called create URNs

**Comment by wlpotter** [comment]
This is fixed; new issue has been created for minting URNs: https://github.com/srophe/caesarea-data/issues/77
