### ISSUE TITLE
Insert TEI:head in every body/listBibl

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea-data#62]
```
<listBibl>
<head>Works Cited</head>
<bibl>
```
```
<listBibl>
<head>Related Editions</head>
<bibl>
```

**Comment by davidamichelson** [comment]
When done please let @wsalesky know and assign https://github.com/srophe/caesarea/issues/235 to here.

**Comment by wlpotter** [comment]
@davidamichelson I'm wondering if we should revisit this. As I've been updating the new template and CSS, I'm realizing we might end up with 3 listBibls:

1. The works cited for the excerpts (which can stay the same and likely be labelled as Works Cited like you proposed above)
2. A list of other editions and translations, which may be the print versions corresponding to the electronic works cited or other editions the editors want to highlight. Again, this can probably be the Related Editions as proposed above.
3. A listBibl for 'Additional Bibliography' that might include non-edition/translation bibliography of relevance to the excerpt. This could be works referenced in a `note[@type="discussion"]` or in the `desc[@type="context"]`. I'm not sure we have examples of such a case yet, but perhaps the editors would want to add such bibls using the form?

It also strikes me that it might be useful to include a `@type` attribute in addition to the `<head>` element for machine-readability?

**Comment by wlpotter** [comment]
I think we decided to keep just the two `<listBibl>`s with each with a `<head>`. The first will be "Works Cited", which will have the xml:ids referenced by the excerpts (pt. 1 above). The second will be "Additional Bibliography", which is a combination of pts. 2 and 3 above. 

Just want to confirm that this is correct.

**Comment by wlpotter** [comment]
Fixed
