### ISSUE TITLE
Remove Anonymous from  Anonymous, Apostolicae constitutiones 46

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea-data#68]
https://caesarea-maritima.org/testimonia/90

**Comment by davidamichelson** [comment]
Test with unknown for author?

**Comment by wlpotter** [comment]
We should be able to test the persName's `@ref` attribute. The VIAF link should either be missing (leaving an empty attribute) or it should be missing the numerical ID. In either case, we should be able to find-and-replace these.

Will we just not have an author name for these records?

**Comment by davidamichelson** [comment]
Okay yes, please do find and replace.
