### ISSUE TITLE
Add `@unit` attributes to tei:citedRange elements?

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#69]
In tei:bibl/citedRange elements, it might be good to start adding `@unit` attributes, particularly as we might be wanting to cite some sources by page number rather than (or in addition to?) sections.

To-do:

- [x] decide on standard designations/abbreviations (e.g. pp, pages, page, p., sec., etc.)
- [x] add to new data template and author form
- [x] update existing data (should all be sections, but may also need to check by hand?)

**Comment by davidamichelson** [comment]
Yes please do!

**Comment by wlpotter** [comment]
@davidamichelson I think we should follow what we did for The Syriac Gazetteer/Syriaca (see [this issue](https://github.com/srophe/srophe-app-data/issues/821) and [these lines in the schema](https://github.com/srophe/srophe-eXist-app/blob/master/documentation/schemas/out/syriacaPlaces.compiled.rng#L2497-L2519)).

These are all aligned with those found in _CMOS 10.42: Scholarly abbreviations_. I will go ahead and add the list to the template and author form for your review.

I will wait to update the existing data until we've sorted out the white space issue (see [this pull request](https://github.com/srophe/caesarea-data/pull/71))

**Comment by wlpotter** [comment]
This should be fixed. I don't think we entered any records so far that are not section numbers, so this should have caught everything.

@davidamichelson do we need an app issue for visualizing or should it work out of the box?

**Comment by davidamichelson** [comment]
Closed and added new issue here: https://github.com/srophe/caesarea/issues/250
