### ISSUE TITLE
normalize seriesStmt

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#74]
There are some variants here that need to be sorted out, e.g.:

https://caesarea-maritima.org/testimonia/1 has level="m" rather than "s"

view-source:https://caesarea-maritima.org/testimonia/90 lacks the ".org" in the series title

May be other variants as well to find.

**Comment by wlpotter** [comment]
only titles in our data are "Caesarea-Maritima.org: A Digital Archive" and "Caesarea-Maritima: A Digital Archive"

only level attributes are "m" and "s"

**Comment by wlpotter** [comment]
@davidamichelson could you remind me which is correct of the two titles?

**Comment by davidamichelson** [comment]
Yes, please use .org: "Caesarea-Maritima.org: A Digital Archive"
