### ISSUE TITLE
Create new URNs

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#77]
The following records do not currently have URNs created for them:

https://caesarea-maritima.org/testimonia/147
https://caesarea-maritima.org/testimonia/148
https://caesarea-maritima.org/testimonia/57
https://caesarea-maritima.org/testimonia/79
https://caesarea-maritima.org/testimonia/90

These will need to be created using TLG numbers or another standard referencing system. If none exists, we will need to come up with a standard way of designating URNs created by our project.

Cf. [this related issue](https://github.com/srophe/caesarea-data/issues/60)

**Comment by wlpotter** [comment]
We should also discuss this process in terms of minting URNs for translations the project editors create. And we might need to have a place in the app where these are stored (I think we may already set up for this last one since the app has an empty CTS registry file https://github.com/srophe/caesarea/blob/master/CTS/cts-registry.xml)

**Comment by davidamichelson** [comment]
We will wait until DTS has more users
