### ISSUE TITLE
New Directory Created in  caesarea-data/draft-data/

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea-data#80]
@wsalesky We created a new directory to hold a data template for testimonia. Is this okay, does it adversely affect the app or the server in anyway to have this directory?

https://github.com/srophe/caesarea-data/commit/877e33cab279987d9dc46e5dfeec503c077c87bb

**Comment by davidamichelson** [comment]
And is it okay to have this .xml file in there? It won't get indexed by the app will it? We don't want it to appear online.

**Comment by wsalesky** [comment]
@davidamichelson This should be fine. Let me know if you see it turning up in search results, it should not.

**Comment by davidamichelson** [comment]
Great thanks!
