### ISSUE TITLE
names and alphabetic order

### ISSUE THREAD

**Issue by josephrife** [srophe/caesarea-data#86]
Can we fix the names of Flavius Josephus and Cornelius Tacitus so that when the user searches under authors the former appears as Joseph under J and the latter appears as Tacitus under T. Looks like only part of that was done before. We need to do this to move toward a soft rollout. thanks

**Comment by wlpotter** [comment]
(Cf. #82 ) I will get the rest of these done today

**Comment by wlpotter** [comment]
These have been updated (changes documented in #82 )
