### ISSUE TITLE
Batch changes to OLD RECORDS to enable editing of current data using CSS author-mode form

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#88]
The following batch changes will need to be run on existing data in order for the CSS author-mode form to display all the editable fields correctly:

- [x] update CSS link from `<?xml-stylesheet type="text/css" href="https://raw.githubusercontent.com/srophe/srophe-xQueries/master/Caesarea-Data-Entry-Phase2/testimonia-entry.css"?>` to `<?xml-stylesheet type="text/css" href="https://raw.githubusercontent.com/srophe/srophe-xQueries/master/Caesarea-Data-Entry-Phase2/testimonia-metadata-entry.css"?>`
- [x] a second change for metadata entry (can be copied from whoever made the first change using regex)
- [x] empty `<desc type="context"/>` added in tei:body under abstract
- [x] empty textual, discussion, translation, discussion notes under the ab elements
- [x] empty notes in body for related-texts; geography; prosopography; and themes

**Comment by davidamichelson** [comment]
Please make a list of empty elements that Winona might expect in the final data template.

**Comment by davidamichelson** [comment]
including the various TEI:notes

**Comment by wlpotter** [comment]
### Nodes to suppress:
- `/TEI/text/body/note`

### Nodes to display

- `/TEI/text/body/ab/note`, the labels can either come from the `note/@type` attribute or they can be generated by the app
- ?? `/TEI/text/body/desc[@type="context"]` (not present in all records, but may be worth displaying above the edition/translation columns on those that do have it)

**Comment by wlpotter** [comment]
The changes have been made to data; app issues should be made from the above comment. @davidamichelson you might need to discuss with the editors and/or Winona first?

**Comment by wlpotter** [comment]
Update: need to come back and check that all these changes are right once the new data is pulled in.

**Comment by wlpotter** [comment]
App issue is here: https://github.com/srophe/caesarea/issues/264

List of changes here was superseded by #103
