### ISSUE TITLE
delete irrelevant testimonia records

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea-data#93]
Moved from: https://github.com/srophe/caesarea/issues/255
From JLR:

> Hi folks. I am finding a few testimonia that made it into the original listing in the Word docx that I gave you, but as you saw it was a rough draft, and I had read all the passages myself. A few of them are not in fact testimonia about Caesarea. We should erase those. ONe is Jerome on Hilary of Poitiers:
Jerome, De viris illustribus 100 are place names attested in Jerome's De viris illustribus 100. This testimonium was written circa 392 CE. This work was likely written in Bethlehem.URI: https://caesarea-maritima.org/testimonia/141
I will send along requests for erasure of a few more as I come across them. I know this sounds drastic but if you check it out you will see, Joe

**Comment by wlpotter** [comment]
This is still in data; need to remove.

**Comment by davidamichelson** [comment]
Delete https://caesarea-maritima.org/testimonia/141
