### ISSUE TITLE
Delete the Chronology Iron IIC

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea-data#95]
Keep Iron Age IIC

**Comment by wlpotter** [comment]
Also make an app issue to delete it from the menus in the browse and search

**Comment by wlpotter** [comment]
Deleted from [the historical-era taxonomy](https://github.com/srophe/caesarea/blob/master/documentation/caesarea-maritima-historical-era-taxonomy.xml)

**Comment by wlpotter** [comment]
Fixed

**Comment by wlpotter** [comment]
This somehow got reverted. Related to #125
